### ISSUE TITLE
FAST: compilation warnings on GCC 5.1

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#74] opened 2015-05-05 15:35 UTC
```
gcc version 5.1.1 20150422 (Red Hat 5.1.1-1) (GCC)

In file included from lib/proto/fast_book.c:2:0:
lib/proto/fast_book.c: In function ‘apply_increment.constprop’:
/home/denis/devel/arbcap/libtrading/include/libtrading/proto/fast_book.h:134:17: warning: array subscript is above array bounds [-Warray-bounds]
   if (set->books[i].secid == secid)
                 ^
lib/proto/fast_book.c: In function ‘fast_books_join’:
/home/denis/devel/arbcap/libtrading/include/libtrading/proto/fast_book.h:134:17: warning: array subscript is above array bounds [-Warray-bounds]
   if (set->books[i].secid == secid)
                 ^
/home/denis/devel/arbcap/libtrading/include/libtrading/proto/fast_book.h:134:17: warning: array subscript is above array bounds [-Warray-bounds]
   if (set->books[i].secid == secid)
                 ^
```

**Comment by penberg** [comment] 2015-05-09 09:02
@mstanichenko Can you please take a look? Perhaps GCC 5.1.1 optimizes the inline functions more aggressively and discovers an off-by-one somewhere? Or then it's just a false positive.

**Comment by mstanichenko** [comment] 2015-05-12 16:57
Hello guys! I was already thinking of the problem. Need to reproduce it as don't know what it could be.
I just compile gcc locally but don't see these warnings. @divaykin, could you please tell what source I can use to get release you were building against? Thanks!

xgcc (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by divaykin** [comment] 2015-05-12 22:32
@mstanichenko just master branch. we've not modified `fast_book.c/.h` lately. if can't be reproduced easily I don't think it make sense to bother much

**Comment by mstanichenko** [comment] 2015-05-12 22:42
@divaykin, I'm sorry for confusion. I meant GCC release. Is it available [here](https://gcc.gnu.org/releases.html)? You must be also using additional optimization flags that might trigger that issue.

**Comment by divaykin** [comment] 2015-05-12 22:47
It's Fedora 22 beta's GCC. Nope, optimization flags are standard i.e.
unmodified Makefile.

Maybe just too bleeding edge compiler.

Best
D

**Comment by mstanichenko** [comment] 2015-05-29 08:26
I was advised that there is a temporary workaround here. Do not use ```-O3``` optimization. Use ```-O2``` for example for the time being.

**Comment by penberg** [comment] 2016-08-18 16:45
I am unable to reproduce with the GCC version from Fedora 23:

```
gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC) 
```

Closing.

**Closed by penberg** 2016-08-18 16:45 UTC
